language: node_js
node_js:
  - "6"

env:
  global:
    - "FTP_USER=travis_deploy"
    - "FTP_PASSWORD=tr4v1sd3pl0y"
    - "PORT=3000"
after_success:
    "tar --exclude='./node_modules' --exclude='./.git' --exclude='./.gitignore' --exclude='./README.md' -cvf deploy.tar . && curl -v --ftp-create-dirs -T deploy.tar -u $FTP_USER:$FTP_PASSWORD ftp://193.10.30.169 --connect-timeout 60"
