language: node_js
node_js:
  - "6"

env:
  global:
    - "FTP_USER=travis_deploy"
    - "FTP_PASSWORD=tr4v1sd3pl0y"
after_success:
    "curl --ftp-create-dirs -T server.js -u $FTP_USER:$FTP_PASSWORD ftp://193.10.30.169/home/travis_deploy"
